-- Generated from C:\Users\vishwak\Downloads\insert_technical_books.sql
-- 130 rows currently present in the supplied file, upserted by unique ISBN.
BEGIN;
-- Digital + physical technical book catalog insert
-- Generated for public.books (title, author, isbn, category, total_copies, available_copies, cover_url, description, digital_reading_url, digital_access_note)
-- Review category names against your existing 100 rows before running.

INSERT INTO public.books
(title, author, isbn, category, total_copies, available_copies, cover_url, description, digital_reading_url, digital_access_note)
VALUES
('The C Programming Language', 'Brian W. Kernighan and Dennis M. Ritchie', '9780131103627', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780131103627-L.jpg', 'The classic reference for the C language, covering syntax, pointers, and systems-level programming fundamentals.', NULL, 'Physical copy only — check library shelf'),
('C++ Primer', 'Stanley B. Lippman, Josee Lajoie, and Barbara E. Moo', '9780321714114', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321714114-L.jpg', 'A thorough introduction to modern C++ covering core language features and the standard library.', NULL, 'Physical copy only — check library shelf'),
('Effective C++', 'Scott Meyers', '9780321334879', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321334879-L.jpg', 'Practical guidelines for writing safer, more efficient C++ code, organized as bite-sized rules.', NULL, 'Physical copy only — check library shelf'),
('Effective Java', 'Joshua Bloch', '9780134685991', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780134685991-L.jpg', 'Best-practice guidance for writing robust, maintainable Java code from a former Java architect at Sun/Google.', NULL, 'Physical copy only — check library shelf'),
('Head First Java', 'Kathy Sierra and Bert Bates', '9780596009205', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780596009205-L.jpg', 'A beginner-friendly, visually-driven introduction to Java and object-oriented programming concepts.', NULL, 'Physical copy only — check library shelf'),
('Fluent Python', 'Luciano Ramalho', '9781491946008', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781491946008-L.jpg', 'An in-depth look at writing idiomatic, Pythonic code using the language''s more advanced features.', NULL, 'Physical copy only — check library shelf'),
('Automate the Boring Stuff with Python', 'Al Sweigart', '9781593279929', 'Programming', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781593279929-L.jpg', 'A practical, project-based introduction to Python aimed at automating everyday tasks.', NULL, 'Physical copy only — check library shelf'),
('Eloquent JavaScript', 'Marijn Haverbeke', 'OPEN-001', 'Programming', 3, 3, NULL, 'A hands-on introduction to JavaScript, covering the language itself, the browser, and Node.js.', 'https://eloquentjavascript.net/', 'Free, open-license (CC) — full text available online'),
('Think Python', 'Allen B. Downey', 'OPEN-002', 'Programming', 3, 3, NULL, 'An introductory computer-science textbook that teaches programming concepts using Python.', 'https://greenteapress.com/wp/think-python-2e/', 'Free, open-license (CC) — full text available online'),
('Beej''s Guide to C Programming', 'Brian Hall', 'OPEN-003', 'Programming', 3, 3, NULL, 'A friendly, freely distributed guide covering C fundamentals through to more advanced topics.', 'https://beej.us/guide/bgc/', 'Free, open-license — full text available online'),
('Introduction to Algorithms', 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein', '9780262046305', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780262046305-L.jpg', 'A comprehensive, rigorous treatment of algorithm design, analysis, and classic data structures.', NULL, 'Physical copy only — check library shelf'),
('Data Structures and Algorithms in Java', 'Robert Lafore', '9780672324536', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780672324536-L.jpg', 'A beginner-friendly walkthrough of core data structures and algorithms implemented in Java.', NULL, 'Physical copy only — check library shelf'),
('Algorithms', 'Robert Sedgewick and Kevin Wayne', '9780321573513', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321573513-L.jpg', 'A widely used algorithms textbook pairing theory with practical Java implementations.', NULL, 'Physical copy only — check library shelf'),
('Cracking the Coding Interview', 'Gayle Laakmann McDowell', '9780984782857', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg', 'A collection of coding interview questions and strategies covering data structures and algorithms.', NULL, 'Physical copy only — check library shelf'),
('Grokking Algorithms', 'Aditya Bhargava', '9781617292231', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781617292231-L.jpg', 'An illustrated, beginner-friendly introduction to common algorithms and when to use them.', NULL, 'Physical copy only — check library shelf'),
('The Algorithm Design Manual', 'Steven S. Skiena', '9781849967204', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781849967204-L.jpg', 'A practical guide to algorithm design with a catalog of problem types and solution techniques.', NULL, 'Physical copy only — check library shelf'),
('Open Data Structures', 'Pat Morin', 'OPEN-004', 'Data Structures', 3, 3, NULL, 'An open textbook covering the implementation and analysis of fundamental data structures.', 'https://opendatastructures.org/', 'Free, open-license (CC) — full text available online'),
('Problem Solving with Algorithms and Data Structures using Python', 'Brad Miller and David Ranum', 'OPEN-005', 'Data Structures', 3, 3, NULL, 'An interactive open textbook teaching data structures and algorithmic problem solving in Python.', 'https://runestone.academy/ns/books/published/pythonds/index.html', 'Free, open textbook — available online'),
('Data Structures and Algorithm Analysis in C++', 'Mark Allen Weiss', '9780132847377', 'Data Structures', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780132847377-L.jpg', 'A rigorous treatment of data structures and algorithm analysis with C++ implementations.', NULL, 'Physical copy only — check library shelf'),
('Database System Concepts', 'Abraham Silberschatz, Henry F. Korth, and S. Sudarshan', '9780078022159', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780078022159-L.jpg', 'A foundational textbook covering relational database theory, design, and implementation.', NULL, 'Physical copy only — check library shelf'),
('Fundamentals of Database Systems', 'Ramez Elmasri and Shamkant B. Navathe', '9780133970777', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780133970777-L.jpg', 'A broad introduction to database design, normalization, and query processing.', NULL, 'Physical copy only — check library shelf'),
('Learning SQL', 'Alan Beaulieu', '9780596520830', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780596520830-L.jpg', 'A practical, example-driven introduction to writing and understanding SQL queries.', NULL, 'Physical copy only — check library shelf'),
('SQL Performance Explained', 'Markus Winand', '9783950307825', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9783950307825-L.jpg', 'Explains how database indexes work and how to write SQL that performs well at scale.', NULL, 'Physical copy only — check library shelf'),
('Designing Data-Intensive Applications', 'Martin Kleppmann', '9781449373320', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg', 'Explores the architecture and trade-offs behind modern distributed data systems.', NULL, 'Physical copy only — check library shelf'),
('NoSQL Distilled', 'Pramod J. Sadalage and Martin Fowler', '9780321826626', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321826626-L.jpg', 'A concise overview of NoSQL database models and when to choose them over relational systems.', NULL, 'Physical copy only — check library shelf'),
('Database Design - 2nd Edition', 'Adrienne Watt', 'OPEN-006', 'Databases', 3, 3, NULL, 'An open textbook covering relational database design principles and normalization.', 'https://opentextbc.ca/dbdesign01/', 'Free, open-license (CC) — full text available online'),
('SQL Notes for Professionals', 'GoalKicker.com community', 'OPEN-007', 'Databases', 3, 3, NULL, 'A free compiled reference covering common SQL syntax and patterns across major database engines.', 'https://goalkicker.com/SQLBook/', 'Free, community-compiled reference — available online'),
('Seven Databases in Seven Weeks', 'Eric Redmond and Jim R. Wilson', '9781941222129', 'Databases', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781941222129-L.jpg', 'A tour of seven different database systems, comparing their data models and use cases.', NULL, 'Physical copy only — check library shelf'),
('HTML and CSS: Design and Build Websites', 'Jon Duckett', '9781118008188', 'Web Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781118008188-L.jpg', 'A visually rich introduction to building web pages using HTML and CSS.', NULL, 'Physical copy only — check library shelf'),
('JavaScript: The Good Parts', 'Douglas Crockford', '9780596517748', 'Web Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780596517748-L.jpg', 'A concise look at the most reliable and well-designed features of the JavaScript language.', NULL, 'Physical copy only — check library shelf'),
('You Don''t Know JS', 'Kyle Simpson', 'OPEN-008', 'Web Development', 3, 3, NULL, 'A deep-dive book series into JavaScript''s core mechanisms, from scope to asynchrony.', 'https://github.com/getify/You-Dont-Know-JS', 'Free to read online'),
('Learning React', 'Alex Banks and Eve Porcello', '9781492051725', 'Web Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781492051725-L.jpg', 'A practical introduction to building user interfaces with React and modern JavaScript.', NULL, 'Physical copy only — check library shelf'),
('Node.js Design Patterns', 'Mario Casciaro and Luciano Mammino', '9781839214110', 'Web Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781839214110-L.jpg', 'Covers architectural and design patterns for building scalable Node.js applications.', NULL, 'Physical copy only — check library shelf'),
('CSS: The Definitive Guide', 'Eric A. Meyer', '9781449393199', 'Web Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449393199-L.jpg', 'A comprehensive reference covering CSS selectors, layout, and styling techniques.', NULL, 'Physical copy only — check library shelf'),
('Speaking JavaScript', 'Axel Rauschmayer', '9781449365035', 'Web Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449365035-L.jpg', 'An in-depth guide to JavaScript aimed at programmers coming from other languages.', NULL, 'Physical copy only — check library shelf'),
('Pro Git', 'Scott Chacon and Ben Straub', 'OPEN-009', 'Web Development', 3, 3, NULL, 'A complete guide to using Git for version control, from basics to internals.', 'https://git-scm.com/book/en/v2', 'Free, open-license — full text available online'),
('Eloquent JavaScript (Web Edition)', 'Marijn Haverbeke', 'OPEN-010', 'Web Development', 3, 3, NULL, 'Covers browser-based JavaScript programming including the DOM and event handling.', 'https://eloquentjavascript.net/', 'Free, open-license (CC) — full text available online'),
('Artificial Intelligence: A Modern Approach', 'Stuart Russell and Peter Norvig', '9780134610993', 'AI & ML', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780134610993-L.jpg', 'The standard, broad textbook covering the foundations and techniques of artificial intelligence.', NULL, 'Physical copy only — check library shelf'),
('Pattern Recognition and Machine Learning', 'Christopher M. Bishop', '9780387310732', 'AI & ML', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780387310732-L.jpg', 'A graduate-level introduction to statistical pattern recognition and machine learning theory.', NULL, 'Physical copy only — check library shelf'),
('Deep Learning', 'Ian Goodfellow, Yoshua Bengio, and Aaron Courville', '9780262035613', 'AI & ML', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780262035613-L.jpg', 'A rigorous, comprehensive textbook covering the mathematics and methods of deep learning.', NULL, 'Physical copy only — check library shelf'),
('Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow', 'Aurelien Geron', '9781492032649', 'AI & ML', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781492032649-L.jpg', 'A practical, code-first guide to building machine learning systems with popular Python libraries.', NULL, 'Physical copy only — check library shelf'),
('Machine Learning Yearning', 'Andrew Ng', 'OPEN-011', 'AI & ML', 3, 3, NULL, 'A practical guide to structuring machine learning projects, written for working engineers.', 'https://www.deeplearning.ai/machine-learning-yearning/', 'Free, author-released — available online'),
('Dive into Deep Learning', 'Aston Zhang, Zachary C. Lipton, Mu Li, and Alexander J. Smola', 'OPEN-012', 'AI & ML', 3, 3, NULL, 'An interactive deep learning textbook combining theory, math, and runnable code.', 'https://d2l.ai/', 'Free, open-source — full text available online'),
('Neural Networks and Deep Learning', 'Michael Nielsen', 'OPEN-013', 'AI & ML', 3, 3, NULL, 'A gentle, intuition-first introduction to neural networks and backpropagation.', 'http://neuralnetworksanddeeplearning.com/', 'Free, author-released — available online'),
('The Hundred-Page Machine Learning Book', 'Andriy Burkov', '9781999579500', 'AI & ML', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781999579500-L.jpg', 'A compact overview of the most important machine learning concepts and algorithms.', NULL, 'Physical copy only — check library shelf'),
('Speech and Language Processing', 'Daniel Jurafsky and James H. Martin', '9780131873216', 'AI & ML', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780131873216-L.jpg', 'A foundational textbook covering natural language processing and computational linguistics.', NULL, 'Physical copy only — check library shelf'),
('Cloud Computing: Concepts, Technology and Architecture', 'Thomas Erl', '9780133387520', 'Cloud', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780133387520-L.jpg', 'Covers core cloud computing concepts, service models, and architectural patterns.', NULL, 'Physical copy only — check library shelf'),
('Architecting the Cloud', 'Michael J. Kavis', '9781118617618', 'Cloud', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781118617618-L.jpg', 'A guide to evaluating and choosing cloud service models for enterprise applications.', NULL, 'Physical copy only — check library shelf'),
('AWS Certified Solutions Architect Study Guide', 'Ben Piper and David Clinton', '9781119713081', 'Cloud', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119713081-L.jpg', 'An exam-focused guide covering AWS services and solutions architecture best practices.', NULL, 'Physical copy only — check library shelf'),
('Amazon Web Services in Action', 'Michael Wittig and Andreas Wittig', '9781617295119', 'Cloud', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781617295119-L.jpg', 'A hands-on introduction to building and deploying applications on AWS.', NULL, 'Physical copy only — check library shelf'),
('Cloud Native Patterns', 'Cornelia Davis', '9781617294297', 'Cloud', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781617294297-L.jpg', 'Explores design patterns for building resilient, cloud-native applications.', NULL, 'Physical copy only — check library shelf'),
('Kubernetes: Up and Running', 'Kelsey Hightower, Brendan Burns, and Joe Beda', '9781492046530', 'Cloud', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781492046530-L.jpg', 'A practical introduction to deploying and managing containerized applications with Kubernetes.', NULL, 'Physical copy only — check library shelf'),
('AWS Well-Architected Framework', 'Amazon Web Services', 'OPEN-014', 'Cloud', 3, 3, NULL, 'AWS''s official guidance for designing secure, reliable, and cost-effective cloud workloads.', 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html', 'Free, official whitepaper — available online'),
('The NIST Definition of Cloud Computing', 'National Institute of Standards and Technology (NIST)', 'OPEN-015', 'Cloud', 3, 3, NULL, 'The widely-cited NIST publication defining cloud service and deployment models.', 'https://csrc.nist.gov/pubs/sp/800/145/final', 'Free, public domain — available online'),
('Practical Cryptography for Developers', 'Svetlin Nakov', 'OPEN-016', 'Cybersecurity', 3, 3, NULL, 'A developer-focused, hands-on guide to modern cryptographic algorithms and their use.', 'https://cryptobook.nakov.com/', 'Free, open-source — available online'),
('The Web Application Hacker''s Handbook', 'Dafydd Stuttard and Marcus Pinto', '9781118026472', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781118026472-L.jpg', 'A detailed guide to discovering and exploiting security flaws in web applications.', NULL, 'Physical copy only — check library shelf'),
('Hacking: The Art of Exploitation', 'Jon Erickson', '9781593271442', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781593271442-L.jpg', 'Covers the fundamentals of exploitation, from programming and networking to cryptography.', NULL, 'Physical copy only — check library shelf'),
('Applied Cryptography', 'Bruce Schneier', '9780471117094', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780471117094-L.jpg', 'A classic, thorough reference covering cryptographic protocols and algorithms.', NULL, 'Physical copy only — check library shelf'),
('Network Security Essentials', 'William Stallings', '9780134527338', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780134527338-L.jpg', 'An accessible introduction to network security principles, protocols, and practices.', NULL, 'Physical copy only — check library shelf'),
('Metasploit: The Penetration Tester''s Guide', 'David Kennedy, Jim O''Gorman, Devon Kearns, and Mati Aharoni', '9781593272883', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781593272883-L.jpg', 'A practical guide to using the Metasploit framework for penetration testing.', NULL, 'Physical copy only — check library shelf'),
('Security Engineering', 'Ross Anderson', '9781119642787', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119642787-L.jpg', 'A broad, systems-level look at building dependable, secure computer systems.', NULL, 'Physical copy only — check library shelf'),
('CISSP All-in-One Exam Guide', 'Shon Harris and Fernando Maymi', '9781260142655', 'Cybersecurity', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781260142655-L.jpg', 'An exam-preparation guide covering the full breadth of information security domains.', NULL, 'Physical copy only — check library shelf'),
('NIST Cybersecurity Framework', 'National Institute of Standards and Technology (NIST)', 'OPEN-017', 'Cybersecurity', 3, 3, NULL, 'The widely adopted NIST framework for managing and reducing cybersecurity risk.', 'https://www.nist.gov/cyberframework', 'Free, public domain — available online'),
('Computer Networking: A Top-Down Approach', 'James F. Kurose and Keith W. Ross', '9780133594140', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780133594140-L.jpg', 'A widely used networking textbook that builds from applications down to the physical layer.', NULL, 'Physical copy only — check library shelf'),
('Computer Networks', 'Andrew S. Tanenbaum and David J. Wetherall', '9780132126953', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780132126953-L.jpg', 'A comprehensive textbook covering network architecture, protocols, and design.', NULL, 'Physical copy only — check library shelf'),
('TCP/IP Illustrated, Volume 1', 'W. Richard Stevens', '9780201633467', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780201633467-L.jpg', 'A detailed, protocol-by-protocol walkthrough of how TCP/IP actually works.', NULL, 'Physical copy only — check library shelf'),
('Computer Networks: A Systems Approach', 'Larry Peterson and Bruce Davie', 'OPEN-018', 'Computer Networks', 3, 3, NULL, 'An open access textbook covering network design from a systems engineering perspective.', 'https://book.systemsapproach.org/', 'Free, open access — available online'),
('Network Warrior', 'Gary A. Donahue', '9781449387860', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449387860-L.jpg', 'A practical, field-guide style book on real-world enterprise networking.', NULL, 'Physical copy only — check library shelf'),
('Routing TCP/IP, Volume 1', 'Jeff Doyle and Jennifer DeHaven Carroll', '9781587052026', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781587052026-L.jpg', 'An in-depth guide to IP routing protocols used in enterprise and ISP networks.', NULL, 'Physical copy only — check library shelf'),
('CCNA Routing and Switching Complete Study Guide', 'Todd Lammle', '9781119288282', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119288282-L.jpg', 'An exam-focused guide covering core networking concepts for the CCNA certification.', NULL, 'Physical copy only — check library shelf'),
('Data Communications and Networking', 'Behrouz A. Forouzan', '9780073376226', 'Computer Networks', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780073376226-L.jpg', 'A foundational textbook covering data communication principles and networking protocols.', NULL, 'Physical copy only — check library shelf'),
('Operating System Concepts', 'Abraham Silberschatz, Peter B. Galvin, and Greg Gagne', '9781119800361', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119800361-L.jpg', 'A foundational textbook covering process management, memory, and file systems.', NULL, 'Physical copy only — check library shelf'),
('Operating Systems: Three Easy Pieces', 'Remzi H. Arpaci-Dusseau and Andrea C. Arpaci-Dusseau', 'OPEN-019', 'Operating Systems', 3, 3, NULL, 'A freely available textbook covering virtualization, concurrency, and persistence in OS design.', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 'Free, open-license — available online'),
('Modern Operating Systems', 'Andrew S. Tanenbaum and Herbert Bos', '9780133591620', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780133591620-L.jpg', 'A broad survey of operating system design, from classic concepts to distributed systems.', NULL, 'Physical copy only — check library shelf'),
('The Linux Programming Interface', 'Michael Kerrisk', '9781593272203', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781593272203-L.jpg', 'A comprehensive reference to Linux and UNIX system programming.', NULL, 'Physical copy only — check library shelf'),
('How Linux Works', 'Brian Ward', '9781718500402', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781718500402-L.jpg', 'An accessible explanation of what happens under the hood of a Linux system.', NULL, 'Physical copy only — check library shelf'),
('Advanced Programming in the UNIX Environment', 'W. Richard Stevens and Stephen A. Rago', '9780321637734', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321637734-L.jpg', 'A definitive guide to UNIX system programming, from files to processes to signals.', NULL, 'Physical copy only — check library shelf'),
('Linux Kernel Development', 'Robert Love', '9780672329463', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780672329463-L.jpg', 'An accessible walkthrough of Linux kernel internals for systems programmers.', NULL, 'Physical copy only — check library shelf'),
('Understanding the Linux Kernel', 'Daniel P. Bovet and Marco Cesati', '9780596005658', 'Operating Systems', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780596005658-L.jpg', 'A detailed exploration of Linux kernel internals, from booting to scheduling.', NULL, 'Physical copy only — check library shelf'),
('Clean Code', 'Robert C. Martin', '9780132350884', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg', 'A guide to writing readable, maintainable code through naming, structure, and testing practices.', NULL, 'Physical copy only — check library shelf'),
('Design Patterns: Elements of Reusable Object-Oriented Software', 'Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides', '9780201633610', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg', 'The classic catalog of object-oriented design patterns, often called the ''Gang of Four'' book.', NULL, 'Physical copy only — check library shelf'),
('The Pragmatic Programmer', 'David Thomas and Andrew Hunt', '9780135957059', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg', 'A collection of practical tips and philosophies for effective software development.', NULL, 'Physical copy only — check library shelf'),
('Code Complete', 'Steve McConnell', '9780735619678', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780735619678-L.jpg', 'A comprehensive guide to software construction practices and code quality.', NULL, 'Physical copy only — check library shelf'),
('Refactoring', 'Martin Fowler', '9780134757599', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780134757599-L.jpg', 'A catalog of techniques for improving code structure without changing its behavior.', NULL, 'Physical copy only — check library shelf'),
('The Mythical Man-Month', 'Frederick P. Brooks Jr.', '9780201835953', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780201835953-L.jpg', 'A classic essay collection on the challenges of managing large software projects.', NULL, 'Physical copy only — check library shelf'),
('Software Engineering', 'Ian Sommerville', '9780133943030', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780133943030-L.jpg', 'A broad textbook covering the software development lifecycle and engineering practices.', NULL, 'Physical copy only — check library shelf'),
('Test-Driven Development by Example', 'Kent Beck', '9780321146533', 'Software Engineering', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321146533-L.jpg', 'Introduces test-driven development through worked examples and practical patterns.', NULL, 'Physical copy only — check library shelf'),
('The Architecture of Open Source Applications', 'Amy Brown and Greg Wilson (editors)', 'OPEN-020', 'Software Engineering', 3, 3, NULL, 'Real-world software architects explain the design decisions behind well-known open source projects.', 'https://aosabook.org/en/index.html', 'Free, open-license (CC) — available online'),
('Designing the Internet of Things', 'Adrian McEwen and Hakim Cassimally', '9781118430620', 'IoT', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781118430620-L.jpg', 'A practical introduction to designing and prototyping connected IoT devices.', NULL, 'Physical copy only — check library shelf'),
('Internet of Things: A Hands-On Approach', 'Arshdeep Bahga and Vijay Madisetti', '9780996025515', 'IoT', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780996025515-L.jpg', 'A project-based introduction to IoT concepts, protocols, and platforms.', NULL, 'Physical copy only — check library shelf'),
('Programming the Internet of Things', 'Andy King', '9781492081394', 'IoT', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781492081394-L.jpg', 'Covers building end-to-end IoT applications, from devices to cloud services.', NULL, 'Physical copy only — check library shelf'),
('Getting Started with the Internet of Things', 'Cuno Pfister', '9781449393571', 'IoT', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449393571-L.jpg', 'An introductory guide to prototyping IoT devices using microcontrollers and sensors.', NULL, 'Physical copy only — check library shelf'),
('IoT Fundamentals', 'David Hanes, Gonzalo Salgueiro, and Patrick Grossetete', '9781587144561', 'IoT', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781587144561-L.jpg', 'Covers foundational IoT networking concepts and architectures used in industry.', NULL, 'Physical copy only — check library shelf'),
('Building the Internet of Things', 'Maciej Kranz', '9781119285663', 'IoT', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119285663-L.jpg', 'Explores real-world IoT implementation strategies for organizations.', NULL, 'Physical copy only — check library shelf'),
('Internet of Things (IoT) Use Cases and Technologies', 'F. John Dian and co-authors', 'OPEN-021', 'IoT', 3, 3, NULL, 'Introduces IoT use cases and the wired and wireless technologies that enable them.', 'https://freecomputerbooks.com/Internet-of-Things-IoT-Use-Cases-and-Technologies.html', 'Free, Creative Commons licensed — available online'),
('Internet of Things (IoT) in 5 Days', 'Multiple contributors', 'OPEN-022', 'IoT', 3, 3, NULL, 'A hands-on guide covering IPv6 networking, sensors, and IoT protocols.', 'https://freecomputerbooks.com/Internet-of-Things-in-5-days.html', 'Free, Creative Commons licensed — available online'),
('Python for Data Analysis', 'Wes McKinney', '9781491957660', 'Data Science', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781491957660-L.jpg', 'A practical guide to data manipulation and analysis using Python''s pandas library.', NULL, 'Physical copy only — check library shelf'),
('An Introduction to Statistical Learning', 'Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani', 'OPEN-023', 'Data Science', 3, 3, NULL, 'An accessible introduction to statistical learning methods with applied examples.', 'https://www.statlearning.com/', 'Free, author-authorized — available online'),
('The Elements of Statistical Learning', 'Trevor Hastie, Robert Tibshirani, and Jerome Friedman', 'OPEN-024', 'Data Science', 3, 3, NULL, 'A more advanced, mathematically rigorous companion covering statistical learning theory.', 'https://hastie.su.domains/ElemStatLearn/', 'Free, author-authorized — available online'),
('Think Stats', 'Allen B. Downey', 'OPEN-025', 'Data Science', 3, 3, NULL, 'An introduction to probability and statistics using Python and real-world datasets.', 'https://greenteapress.com/wp/think-stats-2e/', 'Free, open-license (CC) — available online'),
('Data Science from Scratch', 'Joel Grus', '9781492041139', 'Data Science', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781492041139-L.jpg', 'Builds core data science algorithms from first principles using plain Python.', NULL, 'Physical copy only — check library shelf'),
('Storytelling with Data', 'Cole Nussbaumer Knaflic', '9781119002253', 'Data Science', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119002253-L.jpg', 'A practical guide to designing clear, effective data visualizations.', NULL, 'Physical copy only — check library shelf'),
('Naked Statistics', 'Charles Wheelan', '9780393347777', 'Data Science', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780393347777-L.jpg', 'An approachable, jargon-light introduction to core statistical concepts.', NULL, 'Physical copy only — check library shelf'),
('R for Data Science', 'Hadley Wickham and Garrett Grolemund', 'OPEN-026', 'Data Science', 3, 3, NULL, 'A practical guide to data wrangling, visualization, and modeling using R.', 'https://r4ds.hadley.nz/', 'Free, open-license — available online'),
('Practical Statistics for Data Scientists', 'Peter Bruce and Andrew Bruce', '9781491952962', 'Data Science', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781491952962-L.jpg', 'Covers key statistical concepts data scientists need, with a practical, applied focus.', NULL, 'Physical copy only — check library shelf'),
('Computer Organization and Design', 'David A. Patterson and John L. Hennessy', '9780128201091', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780128201091-L.jpg', 'A widely used textbook connecting hardware design to software performance.', NULL, 'Physical copy only — check library shelf'),
('Computer Architecture: A Quantitative Approach', 'John L. Hennessy and David A. Patterson', '9780128119051', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780128119051-L.jpg', 'An advanced, quantitative treatment of processor and system architecture design.', NULL, 'Physical copy only — check library shelf'),
('Structured Computer Organization', 'Andrew S. Tanenbaum and Todd Austin', '9780132916523', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780132916523-L.jpg', 'Explains computer systems as a series of abstraction layers, from hardware to software.', NULL, 'Physical copy only — check library shelf'),
('Digital Design and Computer Architecture', 'David Harris and Sarah Harris', '9780123944245', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780123944245-L.jpg', 'Bridges digital logic design with computer architecture concepts.', NULL, 'Physical copy only — check library shelf'),
('Computer Systems: A Programmer''s Perspective', 'Randal E. Bryant and David R. O''Hallaron', '9780134092669', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780134092669-L.jpg', 'Explains how programs execute on real hardware, from compilation to memory systems.', NULL, 'Physical copy only — check library shelf'),
('Microprocessor Architecture, Programming, and Applications', 'Ramesh Gaonkar', '9788176566868', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9788176566868-L.jpg', 'Covers microprocessor architecture and assembly-level programming fundamentals.', NULL, 'Physical copy only — check library shelf'),
('The Elements of Computing Systems', 'Noam Nisan and Shimon Schocken', '9780262640688', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780262640688-L.jpg', 'A build-it-yourself journey from logic gates to a working computer and OS (Nand to Tetris).', NULL, 'Physical copy only — check library shelf'),
('Inside the Machine', 'Jon Stokes', '9781593271046', 'Computer Architecture', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781593271046-L.jpg', 'An accessible explanation of how modern microprocessors are designed and how they work.', NULL, 'Physical copy only — check library shelf'),
('Head First Android Development', 'Dawn Griffiths and David Griffiths', '9781491974049', 'Mobile Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781491974049-L.jpg', 'A visually-driven introduction to building Android applications.', NULL, 'Physical copy only — check library shelf'),
('Beginning Flutter: A Hands-On Guide to App Development', 'Marco L. Napoli', '9781119550834', 'Mobile Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781119550834-L.jpg', 'A practical introduction to building cross-platform apps with Flutter and Dart.', NULL, 'Physical copy only — check library shelf'),
('Programming Android', 'Zigurd Mednieks, Laird Dornin, G. Blake Meike, and Masumi Nakamura', '9781449316648', 'Mobile Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449316648-L.jpg', 'Covers Android application architecture and core framework components.', NULL, 'Physical copy only — check library shelf'),
('Mobile Design Pattern Gallery', 'Theresa Neil', '9781449374970', 'Mobile Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781449374970-L.jpg', 'A visual catalog of common UI design patterns used in mobile applications.', NULL, 'Physical copy only — check library shelf'),
('iOS Programming: The Big Nerd Ranch Guide', 'Christian Keur and Aaron Hillegass', '9780135264027', 'Mobile Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780135264027-L.jpg', 'A hands-on introduction to building iOS applications with Swift.', NULL, 'Physical copy only — check library shelf'),
('Android Developer Documentation', 'Google', 'OPEN-027', 'Mobile Development', 3, 3, NULL, 'Google''s official, continuously updated documentation for Android app development.', 'https://developer.android.com/docs', 'Free, official documentation — available online'),
('Flutter Documentation', 'Google', 'OPEN-028', 'Mobile Development', 3, 3, NULL, 'Google''s official documentation and guides for the Flutter cross-platform framework.', 'https://docs.flutter.dev/', 'Free, official documentation — available online'),
('Mobile Computing: Technology, Applications, and Service Creation', 'Asoke K. Talukder and Roopa R. Yavagal', '9780071475020', 'Mobile Development', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780071475020-L.jpg', 'Covers the fundamentals of mobile computing systems, protocols, and services.', NULL, 'Physical copy only — check library shelf'),
('Mastering Bitcoin', 'Andreas M. Antonopoulos', '9781491954386', 'Emerging Tech', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781491954386-L.jpg', 'A technical introduction to how Bitcoin and blockchain technology actually work.', 'https://github.com/bitcoinbook/bitcoinbook', 'Free, open-license (CC BY-SA) — available online'),
('Blockchain Basics', 'Daniel Drescher', '9781484226032', 'Emerging Tech', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781484226032-L.jpg', 'A non-technical, step-by-step introduction to blockchain concepts.', NULL, 'Physical copy only — check library shelf'),
('Mastering Ethereum', 'Andreas M. Antonopoulos and Gavin Wood', '9781491971949', 'Emerging Tech', 3, 3, 'https://covers.openlibrary.org/b/isbn/9781491971949-L.jpg', 'A technical guide to building applications on the Ethereum blockchain.', 'https://github.com/ethereumbook/ethereumbook', 'Free, open-license (CC BY-SA) — available online'),
('Quantum Computing for the Very Curious', 'Andy Matuschak and Michael Nielsen', 'OPEN-029', 'Emerging Tech', 3, 3, NULL, 'An interactive essay introducing the core ideas of quantum computing.', 'https://quantum.country/qcvc', 'Free, author-released — available online'),
('Quantum Computing: An Applied Approach', 'Jack D. Hidary', '9783030239213', 'Emerging Tech', 3, 3, 'https://covers.openlibrary.org/b/isbn/9783030239213-L.jpg', 'A practical introduction to quantum computing aimed at programmers and engineers.', NULL, 'Physical copy only — check library shelf'),
('Learn Quantum Computation Using Qiskit', 'Qiskit Community', 'OPEN-030', 'Emerging Tech', 3, 3, NULL, 'An open, hands-on textbook teaching quantum computing using IBM''s Qiskit framework.', 'https://qiskit.org/learn', 'Free, open-source — available online'),
('Virtual Reality', 'Steven M. LaValle', 'OPEN-031', 'Emerging Tech', 3, 3, NULL, 'A technical introduction to the perception, systems, and engineering behind VR.', 'http://vr.cs.uiuc.edu/', 'Free, author-released — available online'),
('Augmented Reality: Principles and Practice', 'Dieter Schmalstieg and Tobias Hollerer', '9780321883575', 'Emerging Tech', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780321883575-L.jpg', 'Covers the core computer vision and graphics principles behind augmented reality systems.', NULL, 'Physical copy only — check library shelf'),
('Understanding Augmented Reality', 'Alan B. Craig', '9780240824086', 'Emerging Tech', 3, 3, 'https://covers.openlibrary.org/b/isbn/9780240824086-L.jpg', 'An accessible introduction to augmented reality concepts, history, and applications.', NULL, 'Physical copy only — check library shelf')
ON CONFLICT (isbn) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  category = EXCLUDED.category,
  total_copies = EXCLUDED.total_copies,
  available_copies = EXCLUDED.available_copies,
  cover_url = EXCLUDED.cover_url,
  description = EXCLUDED.description,
  digital_reading_url = EXCLUDED.digital_reading_url,
  digital_access_note = EXCLUDED.digital_access_note;

UPDATE public.books SET cover_url = '/book-covers/open-001.svg' WHERE isbn = 'OPEN-001';
UPDATE public.books SET cover_url = '/book-covers/open-002.svg' WHERE isbn = 'OPEN-002';
UPDATE public.books SET cover_url = '/book-covers/open-003.svg' WHERE isbn = 'OPEN-003';
UPDATE public.books SET cover_url = '/book-covers/open-004.svg' WHERE isbn = 'OPEN-004';
UPDATE public.books SET cover_url = '/book-covers/open-005.svg' WHERE isbn = 'OPEN-005';
UPDATE public.books SET cover_url = '/book-covers/open-006.svg' WHERE isbn = 'OPEN-006';
UPDATE public.books SET cover_url = '/book-covers/open-007.svg' WHERE isbn = 'OPEN-007';
UPDATE public.books SET cover_url = '/book-covers/open-008.svg' WHERE isbn = 'OPEN-008';
UPDATE public.books SET cover_url = '/book-covers/open-009.svg' WHERE isbn = 'OPEN-009';
UPDATE public.books SET cover_url = '/book-covers/open-010.svg' WHERE isbn = 'OPEN-010';
UPDATE public.books SET cover_url = '/book-covers/open-011.svg' WHERE isbn = 'OPEN-011';
UPDATE public.books SET cover_url = '/book-covers/open-012.svg' WHERE isbn = 'OPEN-012';
UPDATE public.books SET cover_url = '/book-covers/open-013.svg' WHERE isbn = 'OPEN-013';
UPDATE public.books SET cover_url = '/book-covers/open-014.svg' WHERE isbn = 'OPEN-014';
UPDATE public.books SET cover_url = '/book-covers/open-015.svg' WHERE isbn = 'OPEN-015';
UPDATE public.books SET cover_url = '/book-covers/open-016.svg' WHERE isbn = 'OPEN-016';
UPDATE public.books SET cover_url = '/book-covers/open-017.svg' WHERE isbn = 'OPEN-017';
UPDATE public.books SET cover_url = '/book-covers/open-018.svg' WHERE isbn = 'OPEN-018';
UPDATE public.books SET cover_url = '/book-covers/open-019.svg' WHERE isbn = 'OPEN-019';
UPDATE public.books SET cover_url = '/book-covers/open-020.svg' WHERE isbn = 'OPEN-020';
UPDATE public.books SET cover_url = '/book-covers/open-021.svg' WHERE isbn = 'OPEN-021';
UPDATE public.books SET cover_url = '/book-covers/open-022.svg' WHERE isbn = 'OPEN-022';
UPDATE public.books SET cover_url = '/book-covers/open-023.svg' WHERE isbn = 'OPEN-023';
UPDATE public.books SET cover_url = '/book-covers/open-024.svg' WHERE isbn = 'OPEN-024';
UPDATE public.books SET cover_url = '/book-covers/open-025.svg' WHERE isbn = 'OPEN-025';
UPDATE public.books SET cover_url = '/book-covers/open-026.svg' WHERE isbn = 'OPEN-026';
UPDATE public.books SET cover_url = '/book-covers/open-027.svg' WHERE isbn = 'OPEN-027';
UPDATE public.books SET cover_url = '/book-covers/open-028.svg' WHERE isbn = 'OPEN-028';
UPDATE public.books SET cover_url = '/book-covers/open-029.svg' WHERE isbn = 'OPEN-029';
UPDATE public.books SET cover_url = '/book-covers/open-030.svg' WHERE isbn = 'OPEN-030';
UPDATE public.books SET cover_url = '/book-covers/open-031.svg' WHERE isbn = 'OPEN-031';
COMMIT;
